language: node_js
node_js:
- "4"
- "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install: 
  - node --version | grep -q 'v0.8' && npm install -g npm@2 || true
before_script:
  - npm install -g gulp
  - gem update --system 2.5.1
  - gem --version 
  - gem install sass
  - npm install gulp-ruby-sass
# whitelist
branches:
    - integrationCI    
script:
    - gulp server
    - gulp client
