before_script:
  - npm install -g gulp
  - gem update --system 2.5.1
  - gem --version
install: 
  - gem install sass
  - gulp-ruby-sass
language: node_js
node_js:
- "4"
# whitelist
branches:
    - integrationCI    
script:
    - gulp server
    - gulp client
